### ISSUE TITLE
Send a local push notification when the inbox/messages fetching is complete

### ISSUE THREAD

**Issue by annastoilova** [tiki/app-data#1]
we've finished syncing your inbox

**Comment by ricardobrg** [comment]
With #10 and #11 we can send a local push notification to the user when it is done. 
The push notification should take the user to the decision screen, that will show any new cards.

Acceptance criteria:
1. User receives a push notification when inbox fetching is complete
2. User receives a push notification when messages fetching is complete

**Comment by ricardobrg** [comment]
not applicable
